import { LRParser } from '@lezer/lr';
// This file was generated by lezer-generator. You probably shouldn't edit it.
export const parser = LRParser.deserialize({
  version: 14,
  states:
    "!WQYQPOOOqQPO'#CgOOQO'#Cl'#ClOOQO'#Ch'#ChQYQPOOOOQO,59R,59ROxQPO,59ROOQO-E6f-E6fOOQO1G.m1G.m",
  stateData: '!P~O_OSPOS~ORQOSQOTQOUQOVQOWQOYPO~OXTO~PYOXWO~PYO',
  goto: 'xaPPPPPPPPPPPbhPPPrXQOPSUQSOQUPTVSUXROPSU',
  nodeNames:
    '⚠ LineComment Program Identifier String Number Blue Green Table ) ( Application',
  maxTerm: 16,
  nodeProps: [
    ['openedBy', 9, '('],
    ['closedBy', 10, ')'],
  ],
  skippedNodes: [0, 1],
  repeatNodeCount: 1,
  tokenData:
    "+S~R_XY!QYZ!Q]^!Qpq!Qrs!cst$Pxy'vyz'{}!O(Q!O!P(c!Q![*c!]!^*k!c!}(Q#R#S(Q#T#o(Q~!VS_~XY!QYZ!Q]^!Qpq!Q~!fVOr!crs!{s#O!c#O#P#Q#P;'S!c;'S;=`#y<%lO!c~#QOS~~#TRO;'S!c;'S;=`#^;=`O!c~#aWOr!crs!{s#O!c#O#P#Q#P;'S!c;'S;=`#y;=`<%l!c<%lO!c~#|P;=`<%l!c~$SPrs$V~$YVOr$Vrs$os#O$V#O#P&w#P;'S$V;'S;=`'p<%lO$V~$tPU~!O!P$w~$zP!}#O$}~%QPrs%T~%WVOr%Trs%ms#O%T#O#P%x#P;'S%T;'S;=`&q<%lO%T~%pP#P#Q%s~%xOW~~%{RO;'S%T;'S;=`&U;=`O%T~&XWOr%Trs%ms#O%T#O#P%x#P;'S%T;'S;=`&q;=`<%l%T<%lO%T~&tP;=`<%l%T~&zRO;'S$V;'S;=`'T;=`O$V~'WWOr$Vrs$os#O$V#O#P&w#P;'S$V;'S;=`'p;=`<%l$V<%lO$V~'sP;=`<%l$V~'{OY~~(QOX~~(VSR~}!O(Q!c!}(Q#R#S(Q#T#o(Q~(fP!}#O(i~(lPrs(o~(rVOr(ors)Xs#O(o#O#P)d#P;'S(o;'S;=`*]<%lO(o~)[P#P#Q)_~)dOV~~)gRO;'S(o;'S;=`)p;=`O(o~)sWOr(ors)Xs#O(o#O#P)d#P;'S(o;'S;=`*];=`<%l(o<%lO(o~*`P;=`<%l(o~*hPT~!Q![*c~*pSP~OY*kZ;'S*k;'S;=`*|<%lO*k~+PP;=`<%l*k",
  tokenizers: [0],
  topRules: { Program: [0, 2] },
  tokenPrec: 0,
});